# Generated by Django 4.2.25 on 2025-10-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
