# Generated by Django 4.2.25 on 2025-10-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_volume_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='auditlog_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='auditlog_action_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='auditlog_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['user', 'status'], name='instance_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['status', 'created_at'], name='instance_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['container_id'], name='instance_container_idx'),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['-created_at'], name='instance_created_desc_idx'),
        ),
    ]
