# Generated by Django 4.2.25 on 2025-10-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_database_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='health_check',
            field=models.JSONField(blank=True, default=dict, help_text='Health check configuration, e.g., {"test": ["CMD", "curl", "-f", "http://localhost/"], "interval": 30}'),
        ),
        migrations.AddField(
            model_name='template',
            name='version',
            field=models.CharField(default='1.0', help_text='Template version', max_length=50),
        ),
    ]
